name: assosnation_app
description: AssosNation Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  cloud_firestore: ^1.0.4
  firebase_crashlytics: ^2.0.7
  provider: ^5.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  firebase_storage: ^8.1.0
  google_fonts: ^2.0.0
  date_time_picker: ^2.0.0
  image_picker: ^0.8.1+3
  permission_handler: 8.1.2

  geolocator: ^7.0.3
  google_maps: ^5.1.0
  google_maps_flutter: ^2.0.3
  location: ^4.3.0
  geocoding: ^2.0.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

flutter_native_splash:
  #color: "#009688"
  color: "#FFFFFF"
  image: assets/icon/logo_an_full.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logo_an.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon/
